//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinon_Factory.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecordLogString_zh_TW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecordLogString_zh_TW() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sinon_Factory.Resources.RecordLogString_zh_TW", typeof(RecordLogString_zh_TW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 【BatchOK】 的當地語系化字串。
        /// </summary>
        public static string BatchOK {
            get {
                return ResourceManager.GetString("BatchOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【BatchSave】 的當地語系化字串。
        /// </summary>
        public static string BatchSave {
            get {
                return ResourceManager.GetString("BatchSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【Delete】 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【ExportDOC】 的當地語系化字串。
        /// </summary>
        public static string ExpDoc {
            get {
                return ResourceManager.GetString("ExpDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【ExportODS】 的當地語系化字串。
        /// </summary>
        public static string ExpOds {
            get {
                return ResourceManager.GetString("ExpOds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【ExportPDF】 的當地語系化字串。
        /// </summary>
        public static string ExpPdf {
            get {
                return ResourceManager.GetString("ExpPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【ExportXLS】 的當地語系化字串。
        /// </summary>
        public static string ExpXls {
            get {
                return ResourceManager.GetString("ExpXls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【Insert】 的當地語系化字串。
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【Login Successes】 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【Login Error】 的當地語系化字串。
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【Logout】 的當地語系化字串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 asd 的當地語系化字串。
        /// </summary>
        public static string sadd {
            get {
                return ResourceManager.GetString("sadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【Search】 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【Update】 的當地語系化字串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string 刪除 {
            get {
                return ResourceManager.GetString("刪除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string 新增 {
            get {
                return ResourceManager.GetString("新增", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 國興資訊範例網站 的當地語系化字串。
        /// </summary>
        public static string 系統名稱 {
            get {
                return ResourceManager.GetString("系統名稱", resourceCulture);
            }
        }
    }
}
